language: node_js
node_js:
  - "stable"
services:
  - docker

before_install:
  - docker build -t neeraj2mail-2012/docker-react -f Dockerfile.dev .

script:
  #- docker run neeraj2mail-2012/docker-react npm run test -- --coverage
  - docker run -e CI=true neeraj2mail-2012/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-056817288644"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: AWS_SECRET_KEY