sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t neeraj2mail.2012@gmail.com/docker-react -f Dockerfile.dev .

script:
  - docker run neeraj2mail.2012@gmail.com/docker-react npm run test -- --coverage